/* Lipa: vsebina za nivo A2. Tu dodajaš/urejaš poglavja.
   Vsako poglavje: t = naslov, e = angleški podnaslov, v = besede "slo|eng",
   d = dialog [govorec, slo, eng], g = slovnica (t naslov, h razlaga, q vaje). */
window.LIPA_A2 = [
{t:"Včeraj", e:"Talking about the past",
 v:["prejšnji teden|last week","lani|last year","pred dvema dnevoma|two days ago","bil sem|I was (man)","bila sem|I was (woman)","delal sem|I worked (man)","šla sem|I went (woman)","videl sem|I saw (man)","kupila sem|I bought (woman)","srečati|to meet","zgodaj|early","pozno|late"],
 d:[["Ana","Kaj si delal včeraj?","What did you do yesterday?"],["Miha","Bil sem v Ljubljani.","I was in Ljubljana."],["Ana","Kaj si videl?","What did you see?"],["Miha","Videl sem grad in Tromostovje.","I saw the castle and the Triple Bridge."],["Ana","Jaz sem bila doma in brala knjigo.","I was at home reading a book."],["Miha","Tudi lepo!","That's nice too!"]],
 g:{t:"Past tense: sem delal", h:`<p>The past tense is <b>biti</b> plus a form ending in <b>-l</b>. That ending shows who did it.</p><table class="gt"><tr><td>jaz</td><td><b>sem delal / delala</b></td></tr><tr><td>ti</td><td><b>si delal / delala</b></td></tr><tr><td>on / ona</td><td><b>je delal / delala</b></td></tr><tr><td>mi</td><td><b>smo delali</b></td></tr><tr><td>vi</td><td><b>ste delali</b></td></tr><tr><td>oni</td><td><b>so delali</b></td></tr></table><p class="tip">Men use <b>-l</b>, women <b>-la</b>, groups <b>-li</b>. The little word sem likes second place: <b>Včeraj sem delal.</b></p>`,
  q:[{k:"gap",p:"(woman) Včeraj sem ___ doma.",h:"Yesterday I was at home.",o:["bila","bil","bili"]},{k:"gap",p:"Mi ___ bili v kinu.",h:"We were at the cinema.",o:["smo","sem","so"]},{k:"mc",p:"He worked.",o:["On je delal.","On je delala.","On sem delal."]},{k:"type",p:"(man) I was",a:["bil sem","sem bil","jaz sem bil"]}]}},

{t:"Načrti", e:"Plans and the future",
 v:["naslednji teden|next week","načrt|plan","počitnice|holidays","vikend|weekend","bom|I will","boš|you will","bo|he / she will","obiskati|to visit","potovati|to travel","ostati|to stay","mogoče|maybe","zagotovo|definitely"],
 d:[["Jure","Kaj boš delala ta vikend?","What will you do this weekend?"],["Maja","V soboto bom obiskala babico.","On Saturday I'll visit my grandma."],["Jure","In v nedeljo?","And on Sunday?"],["Maja","Mogoče bom šla v hribe. Greš zraven?","Maybe I'll go to the mountains. Are you coming?"],["Jure","Zagotovo!","Definitely!"]],
 g:{t:"Future: bom delal", h:`<p>The future is <b>bom</b> plus the same <b>-l</b> form you know from the past.</p><table class="gt"><tr><td>jaz</td><td><b>bom</b></td></tr><tr><td>ti</td><td><b>boš</b></td></tr><tr><td>on / ona</td><td><b>bo</b></td></tr><tr><td>mi</td><td><b>bomo</b></td></tr><tr><td>vi</td><td><b>boste</b></td></tr><tr><td>oni</td><td><b>bodo</b></td></tr></table><p class="tip">On its own, bom means <i>I will be</i>: <b>Jutri bom doma.</b></p>`,
  q:[{k:"gap",p:"Jutri ___ doma.",h:"Tomorrow I'll be at home.",o:["bom","boš","bodo"]},{k:"gap",p:"Oni ___ potovali.",h:"They will travel.",o:["bodo","bomo","bo"]},{k:"mc",p:"We will visit.",o:["Obiskali bomo.","Obiskali smo.","Obiskal bom."]},{k:"type",p:"to travel",a:["potovati"]}]}},

{t:"Na potovanju", e:"Travelling",
 v:["vlak|train","letališče|airport","letalo|plane","karta|ticket","povratna karta|return ticket","peron|platform","zamuda|delay","odhod|departure","prihod|arrival","kovček|suitcase","potni list|passport","prenočišče|accommodation"],
 d:[["Potnik","Dober dan, eno povratno karto za Maribor, prosim.","Hello, a return ticket to Maribor, please."],["Blagajničarka","Izvolite. Petnajst evrov.","Here you are. Fifteen euros."],["Potnik","S katerega perona odpelje vlak?","Which platform does the train leave from?"],["Blagajničarka","S tretjega perona, ob desetih.","From platform three, at ten."],["Potnik","Ima vlak zamudo?","Is the train delayed?"],["Blagajničarka","Ne, vozi točno.","No, it's on time."]],
 g:{t:"Kam? or Kje?", h:`<p>Going somewhere and being somewhere use different endings.</p><table class="gt"><tr><td>Kam? (where to)</td><td>Grem <b>v Ljubljano</b>.</td><td>Grem <b>na postajo</b>.</td></tr><tr><td>Kje? (where)</td><td>Sem <b>v Ljubljani</b>.</td><td>Sem <b>na postaji</b>.</td></tr></table><p class="tip">Movement takes <b>-o</b>, location takes <b>-i</b> (for words ending in -a).</p>`,
  q:[{k:"gap",p:"Jutri grem v ___.",h:"Tomorrow I'm going to Ljubljana.",o:["Ljubljano","Ljubljani","Ljubljana"]},{k:"gap",p:"Zdaj sem na ___.",h:"I'm at the station now.",o:["postaji","postajo","postaja"]},{k:"mc",p:"What does \"Kam greš?\" mean?",o:["Where are you going?","Where are you?","When are you going?"]},{k:"type",p:"train",a:["vlak"]}]}},

{t:"Pri zdravniku", e:"At the doctor's",
 v:["zdravnik|doctor (man)","zdravnica|doctor (woman)","bolan|ill (man)","bolna|ill (woman)","Boli me glava.|I have a headache.","Kaj vas boli?|What hurts?","grlo|throat","trebuh|stomach","vročina|fever","prehlad|a cold","tableta|pill","recept|prescription","počivati|to rest"],
 d:[["Zdravnica","Dober dan. Kaj vas boli?","Good day. What hurts?"],["Pacient","Boli me ku...- grlo in imam vročino.","My throat hurts and I have a fever."],["Zdravnica","Od kdaj ste bolni?","Since when have you been ill?"],["Pacient","Od ponedeljka.","Since Monday."],["Zdravnica","Imate prehlad. Tri dni počivajte in pijte čaj.","You have a cold. Rest for three days and drink tea."],["Pacient","Hvala, gospa doktor.","Thank you, doctor."]],
 g:{t:"Boli me: it hurts me", h:`<p>In Slovenian the body part does the hurting, and you are the one it hurts.</p><table class="gt"><tr><td>me</td><td><b>Boli me</b> glava.</td><td>my head hurts</td></tr><tr><td>te</td><td><b>Boli te</b> grlo?</td><td>does your throat hurt?</td></tr><tr><td>ga</td><td><b>Boli ga</b> trebuh.</td><td>his stomach hurts</td></tr><tr><td>jo</td><td><b>Boli jo</b> zob.</td><td>her tooth hurts</td></tr></table><p class="tip">For more than one thing: <b>Bolijo me noge.</b> (My legs hurt.)</p>`,
  q:[{k:"gap",p:"___ me glava.",h:"My head hurts.",o:["Boli","Bolijo","Bolim"]},{k:"gap",p:"Bolijo ___ noge.",h:"My legs hurt.",o:["me","mi","moj"]},{k:"mc",p:"Her throat hurts.",o:["Boli jo grlo.","Boli ga grlo.","Boli me grlo."]},{k:"type",p:"fever",a:["vročina"]}]}},

{t:"Nakupovanje", e:"Shopping",
 v:["cena|price","poceni|cheap","drago|expensive","popust|discount","velikost|size","pomeriti|to try on","blagajna|checkout","plačati|to pay","s kartico|by card","z gotovino|in cash","večji|bigger","manjši|smaller","cenejši|cheaper"],
 d:[["Kupka","Lahko pomerim te hlače?","Can I try on these trousers?"],["Prodajalka","Seveda. Katero velikost rabite?","Of course. What size do you need?"],["Kupka","Premajhne so. Imate večjo velikost?","They're too small. Do you have a bigger size?"],["Prodajalka","Ja, in danes je dvajset odstotkov popusta.","Yes, and today there's twenty percent off."],["Kupka","Odlično! Plačam s kartico.","Great! I'll pay by card."]],
 g:{t:"Comparing: cenejši kot", h:`<p>To compare, add <b>-ejši</b> or <b>-ši</b>, and use <b>kot</b> for <i>than</i>.</p><table class="gt"><tr><td>star</td><td><b>starejši</b></td><td>older</td></tr><tr><td>lep</td><td><b>lepši</b></td><td>nicer</td></tr><tr><td>poceni</td><td><b>cenejši</b></td><td>cheaper</td></tr><tr><td>visok</td><td><b>višji</b></td><td>taller</td></tr><tr><td>velik</td><td><b>večji</b></td><td>bigger</td></tr><tr><td>dober</td><td><b>boljši</b></td><td>better</td></tr></table><p class="tip"><b>Ta plašč je cenejši kot tisti.</b> This coat is cheaper than that one.</p>`,
  q:[{k:"gap",p:"Ta plašč je ___ kot tisti.",h:"This coat is cheaper than that one.",o:["cenejši","cenejša","poceni"]},{k:"mc",p:"better",o:["boljši","dobrejši","bolj dober"]},{k:"gap",p:"Luka je ___ kot Jan.",h:"Luka is taller than Jan.",o:["višji","visokejši","visok"]},{k:"type",p:"cheap",a:["poceni"]}]}},

{t:"V službi", e:"At work",
 v:["služba|job","sodelavec|colleague (man)","sodelavka|colleague (woman)","šef|boss","sestanek|meeting","pisarna|office","računalnik|computer","e-pošta|e-mail","rok|deadline","plača|salary","moram|I must","smem|I'm allowed to"],
 d:[["Šefinja","Ali lahko jutri prideš na sestanek ob devetih?","Can you come to the meeting at nine tomorrow?"],["Tadej","Žal ne morem, zjutraj moram k zdravniku.","Sorry, I can't, I have to go to the doctor in the morning."],["Šefinja","Ni problema. Mi lahko pošlješ poročilo po e-pošti?","No problem. Can you send me the report by e-mail?"],["Tadej","Seveda, do petka.","Of course, by Friday."],["Šefinja","Hvala, odlično.","Thanks, great."]],
 g:{t:"Must, can, may", h:`<table class="gt"><tr><td>must</td><td><b>moram</b> delati</td></tr><tr><td>can</td><td><b>lahko</b> pridem</td></tr><tr><td>may</td><td><b>smem</b> vprašati?</td></tr></table><p>The negatives are special:</p><table class="gt"><tr><td>can't</td><td><b>ne morem</b></td></tr><tr><td>not allowed</td><td><b>ne smem</b></td></tr><tr><td>don't have to</td><td><b>ni treba</b></td></tr></table><p class="tip">Never say <i>ne lahko</i>. For <i>can't</i> it's always <b>ne morem</b>.</p>`,
  q:[{k:"gap",p:"Danes ___ delati.",h:"Today I have to work.",o:["moram","lahko","smem"]},{k:"mc",p:"I can't.",o:["Ne morem.","Ne lahko.","Nimam lahko."]},{k:"gap",p:"Tukaj ne ___ kaditi.",h:"You may not smoke here.",o:["smete","morate","lahko"]},{k:"type",p:"meeting",a:["sestanek"]}]}},

{t:"Prosti čas", e:"Free time",
 v:["prosti čas|free time","hobi|hobby","plavati|to swim","teči|to run","kolesariti|to cycle","hoditi v hribe|to go hiking","igrati kitaro|to play guitar","poslušati glasbo|to listen to music","kuhati|to cook","slikati|to paint","koncert|concert","tekma|match, game"],
 d:[["Nika","Kaj rad počneš v prostem času?","What do you like doing in your free time?"],["Gal","Rad kolesarim in hodim v hribe.","I like cycling and hiking."],["Nika","Jaz pa rada slikam in poslušam glasbo.","And I like painting and listening to music."],["Gal","Greš v petek z mano na koncert?","Will you come to a concert with me on Friday?"],["Nika","Z veseljem!","Gladly!"]],
 g:{t:"Rad + verb: I like doing", h:`<p>Put <b>rad</b> in front of a verb to say you like doing it.</p><table class="gt"><tr><td>man</td><td><b>Rad plavam.</b></td></tr><tr><td>woman</td><td><b>Rada plavam.</b></td></tr><tr><td>we</td><td><b>Radi plavamo.</b></td></tr></table><p class="tip">With igrati, the game or instrument follows directly: <b>igram kitaro, igram nogomet</b>.</p>`,
  q:[{k:"gap",p:"(woman) ___ kuham.",h:"I like cooking.",o:["Rada","Rad","Radi"]},{k:"gap",p:"Radi ___ tenis.",h:"We like playing tennis.",o:["igramo","igram","igrajo"]},{k:"mc",p:"(man) I like swimming.",o:["Rad plavam.","Rad plavati.","Rada plavam."]},{k:"type",p:"to cook",a:["kuhati"]}]}},

{t:"Ljudje", e:"Describing people",
 v:["visok|tall","nizek|short","mlad|young","star|old","lasje|hair","oči|eyes","brada|beard","očala|glasses","prijazen|kind","zabaven|fun","sramežljiv|shy","pameten|clever","Kakšen je?|What is he like?"],
 d:[["Ema","Kakšen je tvoj novi sodelavec?","What's your new colleague like?"],["Rok","Visok je, ima kratke lase in brado.","He's tall, with short hair and a beard."],["Ema","Je prijazen?","Is he nice?"],["Rok","Zelo! Malo sramežljiv, ampak zelo zabaven.","Very! A bit shy, but lots of fun."],["Ema","Ga lahko spoznam?","Can I meet him?"],["Rok","Seveda, pridi jutri na kavo.","Sure, come for coffee tomorrow."]],
 g:{t:"Kakšen, kakšna, kakšno?", h:`<p><i>What is ... like?</i> changes with gender, just like the answer.</p><table class="gt"><tr><td>man</td><td><b>Kakšen</b> je? <b>Visok</b> je.</td></tr><tr><td>woman</td><td><b>Kakšna</b> je? <b>Visoka</b> je.</td></tr></table><p class="tip">Use <b>ima</b> for features, with plural <b>-e</b>: <b>Ima modre oči. Ima dolge lase.</b></p>`,
  q:[{k:"gap",p:"Moja sestra je ___.",h:"My sister is tall.",o:["visoka","visok","visoko"]},{k:"gap",p:"Ima ___ oči.",h:"She has blue eyes.",o:["modre","moder","modra"]},{k:"mc",p:"What is she like?",o:["Kakšna je?","Kakšen je?","Kje je?"]},{k:"type",p:"glasses",a:["očala"]}]}},

{t:"V restavraciji", e:"At a restaurant",
 v:["jedilni list|menu","predjed|starter","glavna jed|main course","sladica|dessert","priloga|side dish","riba|fish","zelenjava|vegetables","solata|salad","krompir|potatoes","čebula|onion","Dober tek!|Enjoy your meal!","napitnina|tip","Mizo za dva, prosim.|A table for two, please."],
 d:[["Natakar","Dober večer. Ste rezervirali?","Good evening. Do you have a reservation?"],["Gost","Ne. Mizo za dva, prosim.","No. A table for two, please."],["Natakar","Izvolite jedilni list.","Here's the menu."],["Gost","Kaj priporočate?","What do you recommend?"],["Natakar","Danes imamo svežo ribo s krompirjem.","Today we have fresh fish with potatoes."],["Gost","Odlično, dvakrat, prosim. In solato brez čebule.","Great, two of those, please. And a salad without onion."]],
 g:{t:"Brez: without", h:`<p>After <b>brez</b>, words change their ending.</p><table class="gt"><tr><td>čebula</td><td>brez <b>čebule</b></td></tr><tr><td>mleko</td><td>brez <b>mleka</b></td></tr><tr><td>sladkor</td><td>brez <b>sladkorja</b></td></tr><tr><td>meso</td><td>brez <b>mesa</b></td></tr></table><p class="tip">Feminine <b>-a</b> becomes <b>-e</b>. Masculine and neuter end in <b>-a</b>. The same form comes after <i>nimam</i>: <b>Nimam časa.</b></p>`,
  q:[{k:"gap",p:"Kavo brez ___, prosim.",h:"Coffee without sugar, please.",o:["sladkorja","sladkor","sladkorju"]},{k:"gap",p:"Solato brez ___.",h:"A salad without onion.",o:["čebule","čebula","čebulo"]},{k:"gap",p:"Čaj brez ___.",h:"Tea without milk.",o:["mleka","mleko","mlekom"]},{k:"type",p:"dessert",a:["sladica"]}]}},

{t:"Iščem stanovanje", e:"Finding a flat",
 v:["najemnina|rent","oglas|advert","lastnik|owner","opremljeno|furnished","stroški|bills","ogled|viewing","nadstropje|floor","dvigalo|lift","parkirišče|parking","ključ|key","sosed|neighbour (man)","soseda|neighbour (woman)","selitev|moving house"],
 d:[["Iva","Dober dan, kličem zaradi oglasa za stanovanje.","Hello, I'm calling about the flat advert."],["Lastnik","Ja, stanovanje je še prosto.","Yes, the flat is still available."],["Iva","Koliko je najemnina?","How much is the rent?"],["Lastnik","Petsto evrov, stroški so posebej.","Five hundred euros, bills are extra."],["Iva","Je opremljeno?","Is it furnished?"],["Lastnik","Ja. Je v tretjem nadstropju, z dvigalom.","Yes. It's on the third floor, with a lift."],["Iva","Lahko pridem jutri na ogled?","Can I come for a viewing tomorrow?"]],
 g:{t:"First, second, third", h:`<table class="gt"><tr><td>1.</td><td><b>prvi</b></td><td>4.</td><td><b>četrti</b></td></tr><tr><td>2.</td><td><b>drugi</b></td><td>5.</td><td><b>peti</b></td></tr><tr><td>3.</td><td><b>tretji</b></td><td>6.</td><td><b>šesti</b></td></tr></table><p>They work like adjectives: <b>prvi dan, prva hiša, prvo nadstropje</b>.</p><p class="tip">On a floor: <b>v prvem / drugem / tretjem nadstropju</b>.</p>`,
  q:[{k:"mc",p:"the third floor",o:["tretje nadstropje","tri nadstropje","tretji nadstropje"]},{k:"gap",p:"To je moj ___ dan v službi.",h:"It's my first day at work.",o:["prvi","prva","ena"]},{k:"gap",p:"Živim v ___ nadstropju.",h:"I live on the second floor.",o:["drugem","drugo","dva"]},{k:"type",p:"rent",a:["najemnina"]}]}},

{t:"Slovenija", e:"Nature and places",
 v:["gora|mountain","hrib|hill","jezero|lake","reka|river","morje|sea","gozd|forest","jama|cave","slap|waterfall","grad|castle","vas|village","dolina|valley","obala|coast","izlet|trip"],
 d:[["Turistka","Kaj priporočaš za izlet?","What do you recommend for a trip?"],["Domačin","Pojdi na Bled. Jezero in grad sta čudovita.","Go to Bled. The lake and the castle are wonderful."],["Turistka","Kaj pa Postojnska jama?","What about Postojna Cave?"],["Domačin","Tudi super, ampak v jami je mrzlo.","Also great, but it's cold in the cave."],["Turistka","In morje?","And the sea?"],["Domačin","Obala je majhna, ampak Piran je zelo lep.","The coast is small, but Piran is very pretty."]],
 g:{t:"More than one: plurals", h:`<table class="gt"><tr><td>feminine -a to -e</td><td>gora, <b>gore</b></td><td>reka, <b>reke</b></td></tr><tr><td>neuter -o to -a</td><td>jezero, <b>jezera</b></td><td>mesto, <b>mesta</b></td></tr><tr><td>masculine + -i / -ovi</td><td>hrib, <b>hribi</b></td><td>grad, <b>gradovi</b></td></tr></table><p class="tip">Remember the dual for exactly two: <b>Jezero in grad sta lepa.</b></p>`,
  q:[{k:"gap",p:"V Sloveniji so lepe ___.",h:"There are beautiful mountains in Slovenia.",o:["gore","gora","goro"]},{k:"mc",p:"Plural of jezero",o:["jezera","jezeri","jezeroi"]},{k:"mc",p:"Plural of grad",o:["gradovi","gradi","grade"]},{k:"type",p:"waterfall",a:["slap"]}]}},

{t:"Mnenja", e:"Feelings and opinions",
 v:["vesel|happy","žalosten|sad","utrujen|tired","jezen|angry","živčen|nervous","presenečen|surprised","Mislim, da ...|I think that ...","Strinjam se.|I agree.","Ne strinjam se.|I disagree.","ker|because","ampak|but","zato|so, that's why","po mojem mnenju|in my opinion"],
 d:[["Sara","Zakaj si tako utrujen?","Why are you so tired?"],["Matej","Ker sem delal do polnoči.","Because I worked until midnight."],["Sara","Mislim, da preveč delaš.","I think you work too much."],["Matej","Strinjam se, ampak projekt je pomemben.","I agree, but the project is important."],["Sara","Zato potrebuješ vikend brez računalnika!","That's why you need a weekend without a computer!"],["Matej","Ja pa jade..","Yes ofcourse...(sarcasm)"]],
 g:{t:"Linking ideas", h:`<table class="gt"><tr><td>because</td><td><b>ker</b></td><td>Doma sem, <b>ker</b> sem bolan.</td></tr><tr><td>that</td><td><b>da</b></td><td>Mislim, <b>da</b> imaš prav.</td></tr><tr><td>but</td><td><b>ampak</b></td><td>Lepo je, <b>ampak</b> drago.</td></tr><tr><td>so</td><td><b>zato</b></td><td>Utrujen sem, <b>zato</b> grem spat.</td></tr></table><p class="tip">Slovenian always puts a comma before <b>da</b>, <b>ker</b> and <b>ki</b>.</p>`,
  q:[{k:"gap",p:"Doma sem, ___ sem bolan.",h:"I'm at home because I'm ill.",o:["ker","zato","ampak"]},{k:"gap",p:"Mislim, ___ imaš prav.",h:"I think you're right.",o:["da","ker","ampak"]},{k:"gap",p:"Utrujena sem, ___ grem spat.",h:"I'm tired, so I'm going to bed.",o:["zato","ker","da"]},{k:"type",p:"I agree.",a:["strinjam se"]}]}}
];
