/* Lipa: vsebina za nivo A1. Tu dodajaš/urejaš poglavja.
   Vsako poglavje: t = naslov, e = angleški podnaslov, v = besede "slo|eng",
   d = dialog [govorec, slo, eng], g = slovnica (t naslov, h razlaga, q vaje). */
window.LIPA_A1 = [
{t:"Pozdravi", e:"Greetings",
 v:["zdravo|hello","živjo|hi","dober dan|good day","dobro jutro|good morning","dober večer|good evening","lahko noč|good night","nasvidenje|goodbye","adijo|bye","hvala|thank you","prosim|please","oprostite|excuse me","ja|yes","ne|no"],
 d:[["Ana","Dober dan!","Good day!"],["Marko","Dober dan! Kako ste?","Good day! How are you?"],["Ana","Dobro, hvala. In vi?","Fine, thanks. And you?"],["Marko","Tudi dobro, hvala.","Also fine, thanks."],["Ana","Nasvidenje!","Goodbye!"],["Marko","Nasvidenje, lep dan!","Goodbye, have a nice day!"]],
 g:{t:"Ti or vi?", h:`<p>Slovenian has two ways to say <i>you</i>.</p><table class="gt"><tr><td>ti</td><td><b>Kako si?</b></td><td>friends, family, children</td></tr><tr><td>vi</td><td><b>Kako ste?</b></td><td>strangers, older people, work</td></tr></table><p class="tip">Vi is also the plural: talking to a group of friends, you say <b>Kako ste?</b></p>`,
  q:[{k:"mc",p:"You meet your best friend. How do you ask how they are?",o:["Kako si?","Kako ste?","Kako sem?"]},{k:"mc",p:"You meet your new boss. How do you ask how they are?",o:["Kako ste?","Kako si?","Kako je?"]},{k:"gap",p:"Dobro, ___. In ti?",h:"Fine, thanks. And you?",o:["hvala","prosim","ne"]},{k:"type",p:"good night",a:["lahko noč"]}]}},

{t:"Kdo sem", e:"Introducing yourself",
 v:["jaz|I","ti|you (informal)","ime|name","Ime mi je ...|My name is ...","Kako ti je ime?|What's your name?","Veseli me.|Nice to meet you.","Od kod si?|Where are you from?","Sem iz Slovenije.|I'm from Slovenia.","Slovenec|Slovenian (man)","Slovenka|Slovenian (woman)","govorim|I speak","malo|a little"],
 d:[["Luka","Živjo! Jaz sem Luka. Kako ti je ime?","Hi! I'm Luka. What's your name?"],["Emma","Živjo, Luka! Ime mi je Emma.","Hi Luka! My name is Emma."],["Luka","Veseli me. Od kod si?","Nice to meet you. Where are you from?"],["Emma","Sem iz Anglije. Pa ti?","I'm from England. And you?"],["Luka","Jaz sem iz Ljubljane.","I'm from Ljubljana."],["Emma","Govorim malo slovensko.","I speak a little Slovenian."]],
 g:{t:"Biti: to be", h:`<table class="gt"><tr><td>jaz</td><td><b>sem</b></td><td>I am</td></tr><tr><td>ti</td><td><b>si</b></td><td>you are</td></tr><tr><td>on / ona</td><td><b>je</b></td><td>he / she is</td></tr><tr><td>mi</td><td><b>smo</b></td><td>we are</td></tr><tr><td>vi</td><td><b>ste</b></td><td>you are (plural, formal)</td></tr><tr><td>oni</td><td><b>so</b></td><td>they are</td></tr></table><p class="tip">Slovenian is famous for the <b>dual</b>, a special form for exactly two people: <b>midva sva</b> (we two are), <b>vidva sta</b> (you two are). You can often drop the pronoun: <b>Sem Luka.</b></p>`,
  q:[{k:"gap",p:"Ti ___ iz Slovenije?",h:"Are you from Slovenia?",o:["si","sem","smo"]},{k:"gap",p:"Mi ___ študenti.",h:"We are students.",o:["smo","ste","so"]},{k:"mc",p:"Which means \"we two are\"?",o:["midva sva","mi smo","vidva sta"]},{k:"type",p:"I am (verb only)",a:["sem","jaz sem"]}]}},

{t:"Številke", e:"Numbers",
 v:["nič|zero","ena|one","dva|two","tri|three","štiri|four","pet|five","šest|six","sedem|seven","osem|eight","devet|nine","deset|ten","dvajset|twenty","sto|one hundred"],
 d:[["Prodajalka","Dober dan! Izvolite.","Good day! What can I get you?"],["Kupec","Tri jabolka, prosim.","Three apples, please."],["Prodajalka","Še kaj?","Anything else?"],["Kupec","Ne, hvala. Koliko stane?","No, thanks. How much is it?"],["Prodajalka","Dva evra.","Two euros."],["Kupec","Izvolite. Hvala!","Here you are. Thanks!"]],
 g:{t:"Counting past ten", h:`<p>For 11 to 19, add <b>-najst</b>:</p><table class="gt"><tr><td>11</td><td><b>enajst</b></td></tr><tr><td>12</td><td><b>dvanajst</b></td></tr><tr><td>15</td><td><b>petnajst</b></td></tr><tr><td>30</td><td><b>trideset</b></td></tr></table><p class="tip">Like in German, the ones come first: 21 is <b>enaindvajset</b>, literally one-and-twenty.</p>`,
  q:[{k:"mc",p:"12",o:["dvanajst","dvajset","dva"]},{k:"mc",p:"25",o:["petindvajset","dvajsetpet","petnajst"]},{k:"mc",p:"What number is enaindvajset?",o:["21","12","11"]},{k:"type",p:"15",a:["petnajst"]}]}},

{t:"Družina", e:"Family",
 v:["družina|family","mama|mum","oče|father","brat|brother","sestra|sister","sin|son","hči|daughter","babica|grandmother","dedek|grandfather","mož|husband","žena|wife","otrok|child","imam|I have"],
 d:[["Nina","Ali imaš brata ali sestro?","Do you have a brother or a sister?"],["Jan","Imam eno sestro. Ime ji je Maja.","I have one sister. Her name is Maja."],["Nina","Koliko je stara?","How old is she?"],["Jan","Stara je deset let.","She's ten years old."],["Nina","Jaz imam dva brata.","I have two brothers."],["Jan","Super!","Great!"]],
 g:{t:"Moj, moja, moje", h:`<p><i>My</i> changes with the gender of the noun.</p><table class="gt"><tr><td>masculine</td><td><b>moj</b> brat</td></tr><tr><td>feminine</td><td><b>moja</b> sestra</td></tr><tr><td>neuter</td><td><b>moje</b> ime</td></tr></table><p class="tip">Quick rule: most feminine nouns end in <b>-a</b>, neuter nouns in <b>-o</b> or <b>-e</b>, and masculine nouns in a consonant.</p>`,
  q:[{k:"gap",p:"___ mama",h:"my mum",o:["moja","moj","moje"]},{k:"gap",p:"___ oče",h:"my father",o:["moj","moja","moje"]},{k:"gap",p:"___ ime",h:"my name",o:["moje","moj","moja"]},{k:"mc",p:"Which noun is feminine?",o:["sestra","brat","otrok"]}]}},

{t:"Hrana in pijača", e:"Food and drink",
 v:["kruh|bread","voda|water","kava|coffee","čaj|tea","mleko|milk","jabolko|apple","sir|cheese","meso|meat","juha|soup","pivo|beer","vino|wine","zajtrk|breakfast","kosilo|lunch","večerja|dinner"],
 d:[["Mama","Kaj boš za zajtrk?","What will you have for breakfast?"],["Tim","Kruh in sir, prosim.","Bread and cheese, please."],["Mama","Kavo ali čaj?","Coffee or tea?"],["Tim","Čaj z mlekom.","Tea with milk."],["Mama","Imaš rad jabolka?","Do you like apples?"],["Tim","Ja, zelo rad!","Yes, a lot!"]],
 g:{t:"Rad imam: I like", h:`<p>To say you like something, use <b>rad imam</b>. The word <i>rad</i> changes with who is speaking.</p><table class="gt"><tr><td>a man says</td><td><b>Rad imam</b> kavo.</td></tr><tr><td>a woman says</td><td><b>Rada imam</b> kavo.</td></tr></table><p class="tip">Notice <b>kava</b> becomes <b>kavo</b> after <i>imam</i>. You'll learn why in the café chapter.</p>`,
  q:[{k:"gap",p:"(woman) ___ imam čaj.",h:"I like tea.",o:["Rada","Rad","Radi"]},{k:"gap",p:"(man) Rad ___ pivo.",h:"I like beer.",o:["imam","sem","je"]},{k:"mc",p:"What is \"večerja\"?",o:["dinner","breakfast","lunch"]},{k:"type",p:"bread",a:["kruh"]}]}},

{t:"V kavarni", e:"At the café",
 v:["kavarna|café","natakar|waiter","Rad bi ...|I would like ... (man)","Rada bi ...|I would like ... (woman)","kozarec|glass","račun|bill","Koliko stane?|How much is it?","izvolite|here you are","Na zdravje!|Cheers!","torta|cake","sladkor|sugar","brez|without"],
 d:[["Natakar","Dober dan. Kaj boste?","Good day. What will you have?"],["Petra","Rada bi eno kavo z mlekom.","I'd like a coffee with milk."],["Natakar","Še kaj?","Anything else?"],["Petra","Ja, en kos torte, prosim.","Yes, a piece of cake, please."],["Petra","Račun, prosim.","The bill, please."],["Natakar","Pet evrov. Hvala lepa.","Five euros. Thank you very much."]],
 g:{t:"Ordering: kava becomes kavo", h:`<p>When you order or want something, feminine nouns change <b>-a</b> to <b>-o</b>.</p><table class="gt"><tr><td>kava</td><td>Rad bi <b>eno kavo</b>.</td></tr><tr><td>voda</td><td>Rada bi <b>vodo</b>.</td></tr><tr><td>torta</td><td>Rad bi <b>torto</b>.</td></tr></table><p class="tip">Most masculine things stay the same: <b>en čaj</b>, <b>en sok</b>.</p>`,
  q:[{k:"gap",p:"Rad bi eno ___.",h:"I'd like a coffee.",o:["kavo","kava","kave"]},{k:"gap",p:"Rada bi ___, prosim.",h:"I'd like water, please.",o:["vodo","voda","vodi"]},{k:"gap",p:"En ___, prosim.",h:"A tea, please.",o:["čaj","čaja","čajo"]},{k:"type",p:"The bill, please.",a:["račun, prosim","račun prosim"]}]}},

{t:"Barve in oblačila", e:"Colours and clothes",
 v:["rdeč|red","moder|blue","zelen|green","rumen|yellow","črn|black","bel|white","majica|T-shirt","hlače|trousers","krilo|skirt","obleka|dress","čevlji|shoes","jakna|jacket","plašč|coat"],
 d:[["Prodajalec","Vam lahko pomagam?","Can I help you?"],["Sara","Iščem modro jakno.","I'm looking for a blue jacket."],["Prodajalec","Tukaj je modra jakna.","Here's a blue jacket."],["Sara","Imate tudi črno?","Do you have a black one too?"],["Prodajalec","Ja, izvolite.","Yes, here you are."],["Sara","Lepa je. Vzamem jo.","It's nice. I'll take it."]],
 g:{t:"Colours match the noun", h:`<p>Adjectives take the same gender as the noun.</p><table class="gt"><tr><td>masculine</td><td><b>rdeč</b> plašč</td></tr><tr><td>feminine</td><td><b>rdeča</b> majica</td></tr><tr><td>neuter</td><td><b>rdeče</b> krilo</td></tr></table><p class="tip">Some adjectives lose an <b>e</b>: moder becomes <b>modra</b> and <b>modro</b>.</p>`,
  q:[{k:"gap",p:"___ majica",h:"a red T-shirt",o:["rdeča","rdeč","rdeče"]},{k:"gap",p:"zeleno ___",h:"a green skirt",o:["krilo","jakna","plašč"]},{k:"gap",p:"črn ___",h:"a black coat",o:["plašč","obleka","krilo"]},{k:"mc",p:"a blue dress",o:["modra obleka","moder obleka","modro obleka"]}]}},

{t:"Dnevi in čas", e:"Days and time",
 v:["ponedeljek|Monday","torek|Tuesday","sreda|Wednesday","četrtek|Thursday","petek|Friday","sobota|Saturday","nedelja|Sunday","danes|today","jutri|tomorrow","včeraj|yesterday","teden|week","ura|hour, o'clock","Koliko je ura?|What time is it?"],
 d:[["Eva","Koliko je ura?","What time is it?"],["Maks","Ura je tri.","It's three o'clock."],["Eva","Kateri dan je danes?","What day is it today?"],["Maks","Danes je petek.","Today is Friday."],["Eva","Super! Jutri je sobota.","Great! Tomorrow is Saturday."],["Maks","Greva v soboto v kino?","Shall we go to the cinema on Saturday?"]],
 g:{t:"On Monday: v ponedeljek", h:`<p>For <i>on</i> a day, use <b>v</b>. Days ending in <b>-a</b> change to <b>-o</b>.</p><table class="gt"><tr><td>ponedeljek</td><td><b>v ponedeljek</b></td></tr><tr><td>sreda</td><td><b>v sredo</b></td></tr><tr><td>sobota</td><td><b>v soboto</b></td></tr><tr><td>nedelja</td><td><b>v nedeljo</b></td></tr></table>`,
  q:[{k:"gap",p:"v ___",h:"on Wednesday",o:["sredo","sreda","sredi"]},{k:"gap",p:"v ___",h:"on Sunday",o:["nedeljo","nedelja","nedelje"]},{k:"mc",p:"on Monday",o:["v ponedeljek","v ponedeljko","na ponedeljek"]},{k:"type",p:"tomorrow",a:["jutri"]}]}},

{t:"V mestu", e:"In the city",
 v:["mesto|city","ulica|street","trgovina|shop","banka|bank","pošta|post office","lekarna|pharmacy","postaja|station","avtobus|bus","levo|left","desno|right","naravnost|straight on","blizu|near","daleč|far","Kje je ...?|Where is ...?"],
 d:[["Turist","Oprostite, kje je pošta?","Excuse me, where is the post office?"],["Gospa","Pojdite naravnost, potem levo.","Go straight on, then left."],["Turist","Je daleč?","Is it far?"],["Gospa","Ne, zelo blizu je.","No, it's very close."],["Turist","Najlepša hvala!","Thank you very much!"],["Gospa","Ni za kaj.","You're welcome."]],
 g:{t:"Where you are: v banki, na pošti", h:`<p>To say <i>at</i> or <i>in</i> a place, use <b>v</b> or <b>na</b>, and the ending becomes <b>-i</b>.</p><table class="gt"><tr><td>banka</td><td><b>v banki</b></td></tr><tr><td>trgovina</td><td><b>v trgovini</b></td></tr><tr><td>pošta</td><td><b>na pošti</b></td></tr><tr><td>postaja</td><td><b>na postaji</b></td></tr></table><p class="tip">Which places take <b>na</b> is a habit to learn word by word. Pošta and postaja always go with na.</p>`,
  q:[{k:"gap",p:"Sem v ___.",h:"I'm at the bank.",o:["banki","banka","banko"]},{k:"gap",p:"Čakam na ___.",h:"I'm waiting at the station.",o:["postaji","postaja","postajo"]},{k:"mc",p:"at the post office",o:["na pošti","v pošti","na pošta"]},{k:"type",p:"left",a:["levo"]}]}},

{t:"Doma", e:"At home",
 v:["hiša|house","stanovanje|flat","soba|room","kuhinja|kitchen","kopalnica|bathroom","spalnica|bedroom","miza|table","stol|chair","postelja|bed","okno|window","vrata|door","balkon|balcony"],
 d:[["Klara","To je moje stanovanje.","This is my flat."],["Rok","Lepo je! Koliko sob imaš?","It's nice! How many rooms do you have?"],["Klara","Imam dve sobi, kuhinjo in kopalnico.","I have two rooms, a kitchen and a bathroom."],["Rok","Imaš tudi balkon?","Do you have a balcony too?"],["Klara","Ja, majhen balkon z rožami.","Yes, a small balcony with flowers."]],
 g:{t:"Imeti: to have", h:`<table class="gt"><tr><td>jaz</td><td><b>imam</b></td></tr><tr><td>ti</td><td><b>imaš</b></td></tr><tr><td>on / ona</td><td><b>ima</b></td></tr><tr><td>mi</td><td><b>imamo</b></td></tr><tr><td>vi</td><td><b>imate</b></td></tr><tr><td>oni</td><td><b>imajo</b></td></tr></table><p class="tip">For <i>don't have</i>, swap the start: <b>nimam, nimaš, nima</b>.</p>`,
  q:[{k:"gap",p:"Ona ___ veliko hišo.",h:"She has a big house.",o:["ima","imam","imajo"]},{k:"gap",p:"Mi ___ balkon.",h:"We have a balcony.",o:["imamo","imate","imajo"]},{k:"gap",p:"Jaz ___ avta.",h:"I don't have a car.",o:["nimam","imam","nima"]},{k:"type",p:"kitchen",a:["kuhinja"]}]}},

{t:"Moj dan", e:"My day",
 v:["delati|to work","spati|to sleep","jesti|to eat","piti|to drink","brati|to read","govoriti|to speak","iti|to go","vstati|to get up","zjutraj|in the morning","popoldne|in the afternoon","zvečer|in the evening","vedno|always","včasih|sometimes"],
 d:[["Tina","Kdaj vstaneš?","When do you get up?"],["Bor","Vstanem ob sedmih.","I get up at seven."],["Tina","Kaj delaš popoldne?","What do you do in the afternoon?"],["Bor","Popoldne delam, zvečer berem.","In the afternoon I work, in the evening I read."],["Tina","Jaz zvečer vedno gledam filme.","I always watch films in the evening."]],
 g:{t:"I do, you do", h:`<p>In the present tense, the <i>I</i> form ends in <b>-m</b> and the <i>you</i> form in <b>-š</b>.</p><table class="gt"><tr><td>delati</td><td><b>delam</b></td><td><b>delaš</b></td></tr><tr><td>govoriti</td><td><b>govorim</b></td><td><b>govoriš</b></td></tr><tr><td>brati</td><td><b>berem</b></td><td><b>bereš</b></td></tr><tr><td>piti</td><td><b>pijem</b></td><td><b>piješ</b></td></tr></table>`,
  q:[{k:"gap",p:"Jaz ___ slovensko.",h:"I speak Slovenian.",o:["govorim","govoriš","govori"]},{k:"gap",p:"Ti ___ knjigo?",h:"Are you reading a book?",o:["bereš","berem","bere"]},{k:"mc",p:"I drink",o:["pijem","pije","piti"]},{k:"type",p:"I work",a:["delam","jaz delam"]}]}},

{t:"Vreme", e:"Weather and seasons",
 v:["vreme|weather","sonce|sun","dež|rain","sneg|snow","veter|wind","toplo|warm","mrzlo|cold","Dežuje.|It's raining.","Sneži.|It's snowing.","pomlad|spring","poletje|summer","jesen|autumn","zima|winter"],
 d:[["Lara","Kakšno je vreme danes?","What's the weather like today?"],["Žan","Mrzlo je in sneži.","It's cold and snowing."],["Lara","Imaš rad zimo?","Do you like winter?"],["Žan","Ne, raje imam poletje.","No, I prefer summer."],["Lara","Jaz tudi. Poleti greva na morje!","Me too. In summer we're going to the seaside!"]],
 g:{t:"No \"it\" needed", h:`<p>Weather sentences don't need a word for <i>it</i>:</p><table class="gt"><tr><td>It's raining.</td><td><b>Dežuje.</b></td></tr><tr><td>It's snowing.</td><td><b>Sneži.</b></td></tr><tr><td>It's warm.</td><td><b>Toplo je.</b></td></tr></table><p class="tip">Seasons have their own <i>in</i> forms: <b>spomladi, poleti, jeseni, pozimi</b>.</p>`,
  q:[{k:"mc",p:"in winter",o:["pozimi","v zima","zimi"]},{k:"mc",p:"It's raining.",o:["Dežuje.","Je dež.","Dež je dežuje."]},{k:"gap",p:"Poleti je ___.",h:"In summer it's warm.",o:["toplo","mrzlo","sneži"]},{k:"type",p:"snow",a:["sneg"]}]}}
];
